export const veg_pizza = [
  {
    id: 1,
    img: "/img/pizza2.jpg",
    title: "Deluxe Veggie Pizza.",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 2,
    img: "/img/pizza3.jpg",
    title: "Veg Extravaganza Pizza.",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 3,
    img: "/img/pizza4.jpg",
    title: "Cheese n Corn Pizza.",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 4,
    img: "/img/pizza1.jpg",
    title: "Margherita Pizza.",
    curr_price: "209",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
];

export const non_veg_pizza = [
  {
    id: 5,
    img: "/img/pizza1.jpg",
    title: "Louis Pizza",
    curr_price: 249,
    discount: "50",
    prev_price: 400,
    count: 0,
  },
  {
    id: 6,
    img: "/img/pizza2.jpg",
    title: "Detroit Pizza",
    curr_price: 249,
    discount: "50",
    prev_price: 400,
    count: 0,
  },
  {
    id: 7,
    img: "/img/pizza3.jpg",
    title: "California Pizza",
    curr_price: 249,
    discount: "50",
    prev_price: 400,
    count: 0,
  },
  {
    id: 8,
    img: "/img/pizza4.jpg",
    title: "Chicken Sausage Pizza",
    curr_price: 249,
    discount: "50",
    prev_price: 400,
    count: 0,
  },
];

export const burger_pizza = [
  {
    id: 9,
    img: "/img/pizza1.jpg",
    title: "Sicilian Pizza",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 10,
    img: "/img/pizza3.jpg",
    title: "California Pizza",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 11,
    img: "/img/pizza4.jpg",
    title: "Louis Pizza",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
  {
    id: 12,
    img: "/img/pizza2.jpg",
    title: "Greek Pizza",
    curr_price: "249",
    discount: "50",
    prev_price: "400",
    count: 0,
  },
];
